
export interface LibraryExercise {
  id?: string;
  name: string;
  category: string;
  videoUrl?: string;
  isStandard?: boolean;
}

export const EXERCISES_DB: LibraryExercise[] = [
  // TRÍCEPS
  { name: 'Tríceps Testa na Polia Baixa com Barra W', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=GcrbHqi1JQk', isStandard: true },
  { name: 'Tríceps Testa com Halter', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=Ag3E42fpkmg', isStandard: true },
  { name: 'Tríceps Testa com Barra W', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=J2g1cJ2lNOg', isStandard: true },
  { name: 'Tríceps Testa com Barra W no Banco Declinado', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=YNimvpXBU_o', isStandard: true },
  { name: 'Tríceps Testa com Banco Inclinado na Polia', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=_BBYh0fQEis', isStandard: true },
  { name: 'Tríceps Supinado com Barra', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=1WJpOCvCsW8', isStandard: true },
  { name: 'Tríceps Pulley com Pegada Invertida', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=tJTRGimyrcw', isStandard: true },
  { name: 'Tríceps Pulley com Corda', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=xBXZcsiugvY', isStandard: true },
  { name: 'Tríceps Pulley com Barra Reta', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=wQdCw93LkcI', isStandard: true },
  { name: 'Tríceps no Banco', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=EPNa4oCa8KY', isStandard: true },
  { name: 'Tríceps nas Paralelas na Máquina', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=OhZel-HFo6U', isStandard: true },
  { name: 'Tríceps nas Paralelas', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=yeSNSgTbHlE', isStandard: true },
  { name: 'Tríceps Francês Unilateral', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=zPAfW4JyUTI', isStandard: true },
  { name: 'Tríceps Francês Simultâneo na Polia Alta', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=ytdDPCa36Nk', isStandard: true },
  { name: 'Tríceps Francês Simultâneo', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=Z3Gt3cv-KmE', isStandard: true },
  { name: 'Tríceps Francês na Polia Baixa Unilateral', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=nXQZl0ZrTHg', isStandard: true },
  { name: 'Tríceps Coice no Cabo', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=Mgf3BBYWpRA', isStandard: true },
  { name: 'Tríceps Coice com Halter Simultâneo', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=ydI8u8cbSjc', isStandard: true },
  { name: 'Flexão de Braço para Tríceps', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=QUrO2j-hkC4', isStandard: true },

  // PEITO
  { name: 'Supino Reto na Máquina', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=FNCUgDqFekc', isStandard: true },
  { name: 'Supino Reto com Barra', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=lLswADCMxtM', isStandard: true },
  { name: 'Supino Lateral na Máquina', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=vNZ9eaox6Ng', isStandard: true },
  { name: 'Supino Reto no Smith', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=D8QjO4goFbU', isStandard: true },
  { name: 'Supino Reto com Halter', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=xmByc2VvcdU', isStandard: true },
  { name: 'Supino Inclinado no Smith', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=w3UIZt2k62o', isStandard: true },
  { name: 'Supino Declinado no Smith', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=xq_jmTwljWM', isStandard: true },
  { name: 'Supino Inclinado com Halter', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=QShqY7uQDTc', isStandard: true },
  { name: 'Supino Inclinado com Barra', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=ey9AWZDWzRk', isStandard: true },
  { name: 'Supino Declinado com Halter', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=kqstgkmRHxg', isStandard: true },
  { name: 'Supino Declinado com Barra', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=SM0-rsksTuE', isStandard: true },
  { name: 'Cross Over', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=FqRhJph8pgw', isStandard: true },
  { name: 'Cross Over na Polia Baixa', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=yDk3vn7yZE8', isStandard: true },
  { name: 'Crucifixo Inclinado', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=-zwnICGm7Bo', isStandard: true },
  { name: 'Crucifixo Declinado com Halter', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=SUeSldqUu8U', isStandard: true },
  { name: 'Crucifixo Reto com Halteres', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=pfGsnpWQ3X8', isStandard: true },
  { name: 'Crucifixo Inclinado no Cabo', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=U2nhuiummEM', isStandard: true },
  { name: 'Crucifixo Reto na Máquina', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=vwdxb8byEjc', isStandard: true },
  { name: 'Crucifixo na Máquina com Tronco Inclinado', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=HhvsJDy3lXU', isStandard: true },
  { name: 'Crucifixo Reto no Cabo', category: 'Peito', videoUrl: 'https://www.youtube.com/watch?v=gjhYmqMRZUU', isStandard: true },

  // BÍCEPS
  { name: 'Rosca Scott no Banco Invertido (Spider)', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=Z7EylgZS2zw', isStandard: true },
  { name: 'Rosca Direta com Halter', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=6O_hVOEArG4', isStandard: true },
  { name: 'Rosca Direta com Barra Reta', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=ioqAYxjqIAo', isStandard: true },
  { name: 'Rosca Bíceps Spider no Banco 45 Graus', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=RNwazgfZoh8', isStandard: true },
  { name: 'Rosca Bíceps no Banco Scott com Barra W', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=3C8DbtQE18U', isStandard: true },
  { name: 'Rosca Bíceps no Banco Inclinado a 60 Graus', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=suaavivt_7Q', isStandard: true },
  { name: 'Rosca Bíceps na Polia Baixa', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=_ziU37WD50I', isStandard: true },
  { name: 'Rosca Bíceps na Polia Baixa Pegada Invertida', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=52XLRyEFzQ8', isStandard: true },
  { name: 'Rosca Bíceps na Polia Alta Deitado sobre o Banco', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=boCsCVro2iQ', isStandard: true },
  { name: 'Rosca Bíceps na Polia Alta com o Tronco Inclinado', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=_g7KPzGYq5U', isStandard: true },
  { name: 'Rosca Bíceps Concentrada', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=5AtYejgxabA', isStandard: true },
  { name: 'Rosca Bíceps Concentrada em Pé', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=6lu_v7ZYM0s', isStandard: true },
  { name: 'Rosca Bíceps com Barra Reta Pegada Aberta', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=ye6UMLP9TwU', isStandard: true },
  { name: 'Rosca Bíceps com Barra Pegada Invertida', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=uupLUSamSiQ', isStandard: true },
  { name: 'Rosca Bíceps com Barra Reta Agachado', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=RMwGwaOfQUk', isStandard: true },
  { name: 'Rosca Bíceps Alternada com Rotação', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=-Uap6FEU9ro', isStandard: true },
  { name: 'Rosca Bíceps Unilateral de Lado no Banco Scott', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=jxydon2_uHE', isStandard: true },

  // COSTAS
  { name: 'Remada Serrote', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=n-P88kYWAW4', isStandard: true },
  { name: 'Remada na Máquina Pegada Fechada', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=t7qEY6_gM2E', isStandard: true },
  { name: 'Remada na Máquina Pegada Aberta', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=pLNGbHvV2qM', isStandard: true },
  { name: 'Remada Horizontal com Triângulo', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=h1saOFe5Xuw', isStandard: true },
  { name: 'Remada Horizontal com Barra Neutra', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=KEBk9DW-3FI', isStandard: true },
  { name: 'Remada Horizontal com Barra Longa', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=qpPJ2pAhQI4', isStandard: true },
  { name: 'Remada Curvada Pegada Fechada e Supinada', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=XLOLC19cP9E', isStandard: true },
  { name: 'Remada Curvada Pegada Fechada e Supinada no Smith', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=tP4tL-gfSw0', isStandard: true },
  { name: 'Remada Curvada Pegada Fechada e Supinada no Cabo', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=MHBXevjOIH4', isStandard: true },
  { name: 'Remada Curvada Pegada Fechada e Pronada', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=D6DS2tBPdBQ', isStandard: true },
  { name: 'Remada Curvada Pegada Fechada e Pronada no Smith', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=bEJJPy2X1Lc', isStandard: true },
  { name: 'Remada Curvada Pegada Fechada e Pronada no Cabo', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=PIkl5cIZ70c', isStandard: true },
  { name: 'Remada Curvada Pegada Aberta', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=WGOZ07-WFes', isStandard: true },
  { name: 'Remada Curvada Pegada Aberta no Smith', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=VCTyu9EnLF4', isStandard: true },
  { name: 'Remada Curvada Pegada Aberta no Cabo', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=ChwBihcUdn0', isStandard: true },
  { name: 'Remada Alta com Cabo', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=NnuG9S3fdZM', isStandard: true },
  { name: 'Remada Alta com Barra', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=MV1xWyVgWbQ', isStandard: true },
  { name: 'Remada com Triângulo e Barra Transversal', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=iHACvTxQcdM', isStandard: true },
  { name: 'Pulley Frente com Triângulo', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=E8UZyjVxRO8', isStandard: true },
  { name: 'Pulley Frente com Barra Neutra', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=iHrG2upJyoY', isStandard: true },
  { name: 'Pulley Frente com Barra Longa', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=9KbyqSVh0RQ', isStandard: true },
  { name: 'Pulley Frente com Pegada Supinada', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=RaBOHR9eqxA', isStandard: true },
  { name: 'Pulley Costas com Barra Longa', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=nI0dS2hHK0I', isStandard: true },
  { name: 'Pull Over na Polia Alta com Corda', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=HIswXF8CFTA', isStandard: true },
  { name: 'Pull Over na Polia com Barra Longa', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=4IPaK28a8Ig', isStandard: true },
  { name: 'Pull Over com Dumbbell', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=XqVD3Ouo46U', isStandard: true },
  { name: 'Barra Fixa com Pegada Neutra', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=LBeGixpmINs', isStandard: true },
  { name: 'Barra Fixa com Pegada Aberta', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=x28czgloVE8', isStandard: true },
  { name: 'Barra Livre Costas', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=PD23pTt-NC4', isStandard: true },
  { name: 'Crucifixo Invertido na Polia Baixa', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=732GM__Fr90', isStandard: true },
  { name: 'Crucifixo Invertido com Tronco Inclinado', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=EeLsc3aGMas', isStandard: true },
  { name: 'Crucifixo Invertido no Banco Inclinado', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=yC1Uh26vX8A', isStandard: true },
  { name: 'Crucifixo Invertido na Máquina', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=iVwOmlHa_MI', isStandard: true },

  // GLÚTEOS
  { name: 'Ponte para Glúteos Unilateral', category: 'Glúteo', videoUrl: 'https://www.youtube.com/watch?v=2qBIZo4ngpA', isStandard: true },
  { name: 'Ponte para Glúteos com Dumbbell', category: 'Glúteo', videoUrl: 'https://www.youtube.com/watch?v=em7hywLC7m8', isStandard: true },
  { name: 'Ponte para Glúteos com Barra e Costas no Banco', category: 'Glúteo', videoUrl: 'https://www.youtube.com/watch?v=i8XB5XpS0fo', isStandard: true },

  // PERNAS
  { name: 'Flexora Unilateral em Pé', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=_fmylE6D2aA', isStandard: true },
  { name: 'Flexão Nórdica', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=yBBYRZXL89k', isStandard: true },
  { name: 'Mesa Flexora', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=vYZyCgHTxxY', isStandard: true },
  { name: 'Cadeira Flexora', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=MBkOK2w1MLM', isStandard: true },
  { name: 'Stiff no Cabo', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=tta81ZWLczM', isStandard: true },
  { name: 'Stiff no Smith', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=UUtANmvVIKc', isStandard: true },
  { name: 'Stiff com Barra', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=-stk_aJPGgY', isStandard: true },
  { name: 'Bom Dia', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=3XX81Ukei8E', isStandard: true },
  { name: 'Leg Press Horizontal', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=vvNXP3IDt8A', isStandard: true },
  { name: 'Leg Press no Smith', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=xubDDXdiTNs', isStandard: true },
  { name: 'Leg Press 45 Graus', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=eKB1VQ9SfpA', isStandard: true },
  { name: 'Levantamento Terra', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=B4AzvGWClqk', isStandard: true },
  { name: 'Cadeira Abdutora', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=df5fcakxBPk', isStandard: true },
  { name: 'Cadeira Adutora', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=ceBfZgqkFvU', isStandard: true },
  { name: 'Cadeira Extensora', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=mvRicwRRpgM', isStandard: true },
  { name: 'Agachamento Frontal', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=T_8_CQQQiRY', isStandard: true },
  { name: 'Agachamento com Barra Hexagonal', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=TjKozt4EkYw', isStandard: true },
  { name: 'Agachamento no Hack Invertido', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=ZIJZUpqkie4', isStandard: true },
  { name: 'Agachamento Sumô com Dumbbell e Step', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=u5mwvsgR9ow', isStandard: true },
  { name: 'Agachamento Sumô no Smith', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=6X0CTjEHIyY', isStandard: true },
  { name: 'Agachamento Livre Completo', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=93XU7wP8Jqw', isStandard: true },
  { name: 'Agachamento Livre com o Peso do Corpo', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=gC5WDrdXzMQ', isStandard: true },
  { name: 'Agachamento no Smith', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=ifFuBzaSybY', isStandard: true },
  { name: 'Agachamento na Máquina', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=lh3fG-18LuA', isStandard: true },
  { name: 'Agachamento Ajoelhado', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=y1g6-HurLRE', isStandard: true },
  { name: 'Sissy Squat', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=SXMkOA8IZm0', isStandard: true },
  { name: 'Agachamento com Halteres', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=FVY5iwIhL5U', isStandard: true },
  { name: 'Afundo com Halter e Perna Traseira no Banco', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=vaYhPN48VVM', isStandard: true },
  { name: 'Afundo no Smith com Step no Pé da Frente', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=yq_bgGemBZ8', isStandard: true },
  { name: 'Afundo no Smith com Step nos Dois Pés', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=1KaOqxw25iQ', isStandard: true },
  { name: 'Afundo no Hack', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=UfEoBnPE3JY', isStandard: true },
  { name: 'Avanço com Passada', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=s9LedaLai2I', isStandard: true },
  { name: 'Afundo com Halter', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=b_m5WwQFOiQ', isStandard: true },
  { name: 'Recuo com Halter', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=F2QA6WcbPc8', isStandard: true },
  { name: 'Subida no Banco', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=tcEneamezFg', isStandard: true },
  { name: 'Descida no Banco', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=fqDowIljKR0', isStandard: true },
  { name: 'Panturrilha no Leg Press 45º', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=2wZuAIUIoRQ', isStandard: true },
  { name: 'Panturrilha em Pé sobre Step', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=NXYrjRMw-T8', isStandard: true },
  { name: 'Panturrilha com Step com Peso do Corpo', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=PSeAqaenWqY', isStandard: true },
  { name: 'Gêmeos Sentado', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=OfXCcW7kmEI', isStandard: true },
  { name: 'Panturrilha no Smith sobre Step', category: 'Pernas', videoUrl: 'https://www.youtube.com/watch?v=Sgf4TY2RkJk', isStandard: true },

  // OMBROS
  { name: 'Arnold Press', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=W3LiYfMFzpQ', isStandard: true },
  { name: 'Desenvolvimento com Barra pela Frente', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=uzvFUPbJh3E', isStandard: true },
  { name: 'Desenvolvimento com Barra pela Frente no Smith', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=3IuNFXG-aNI', isStandard: true },
  { name: 'Desenvolvimento com Halter', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=UZhToke0sCk', isStandard: true },
  { name: 'Desenvolvimento na Máquina Aberto', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=cdyTJSiQLUQ', isStandard: true },
  { name: 'Desenvolvimento na Máquina Fechado', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=XuMePHKeZD0', isStandard: true },
  { name: 'Elevação Lateral', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=5JiBneZ5HW4', isStandard: true },
  { name: 'Elevação Frontal Alternada', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=GbyE4ckUu_E', isStandard: true },
  { name: 'Elevação Frontal com Barra W', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=zc1EI5DYK9s', isStandard: true },
  { name: 'Elevação Frontal com Banco Inclinado a 60 Graus', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=3B1tU2Cs6d8', isStandard: true },
  { name: 'Elevação Frontal com Barra no Banco Inclinado a 45 Graus', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=1Z05S2vH5Ok', isStandard: true },
  { name: 'Elevação Frontal com Cabo na Corda', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=CoCdm3_63UE', isStandard: true },
  { name: 'Elevação Unilateral no Banco 45 Graus', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=zAewSpWu3ho', isStandard: true },
  { name: 'Elevação Unilateral no Cabo Baixo', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=SjbOVGz5tH4', isStandard: true },
  { name: 'Encolhimento pela Frente no Smith', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=lUC_sNebRYA', isStandard: true },
  { name: 'Encolhimento com Halteres', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=rXxjturw02s', isStandard: true },
  { name: 'Encolhimento por Trás no Smith', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=vKXz4UsIVlU', isStandard: true },
  { name: 'Rotação Interna de Ombro na Polia', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=9jS0CyZ4bL4', isStandard: true },
  { name: 'Rotação Externa de Ombro na Polia', category: 'Ombros', videoUrl: 'https://www.youtube.com/watch?v=qczjEeYrono', isStandard: true },

  // CORE (ABDOMINAL)
  { name: 'Abdominal no Solo', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=d-nzPNr9b2w', isStandard: true },
  { name: 'Abdominal no Banco Declinado', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=0YqGk8KPPbk', isStandard: true },
  { name: 'Abdominal no Banco Pulley', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=kJFhCFGOhjs', isStandard: true },
  { name: 'Abdominal na Máquina', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=4SR93vi2ZKw', isStandard: true },
  { name: 'Abdominal na Bola', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=Yqfsk_kb1xA', isStandard: true },
  { name: 'Abdominal no Cabo Alto', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=RXlO_LaEozQ', isStandard: true },
  { name: 'Abdominal no Rolinho', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=bwdPuXhgTcQ', isStandard: true },
  { name: 'Abdominal no Rolinho em Pé', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=XfR1ctB6I_w', isStandard: true },
  { name: 'Abdominal Infra no Solo', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=-l1IHdexcA0', isStandard: true },
  { name: 'Abdominal Infra no Smith', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=17Xl_deXAyc', isStandard: true },
  { name: 'Abdominal Infra no Banco Declinado', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=kWIbp3F_gNw', isStandard: true },
  { name: 'Abdominal Infra na Polia Baixa', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=lqOVhzT2by0', isStandard: true },
  { name: 'Abdominal Infra nas Paralelas', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=xPV1lIF75FI', isStandard: true },
  { name: 'Abdominal Infra Suspenso', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=iWnbivr9OxY', isStandard: true },
  { name: 'Abdominal Infra com Rotação na Prancha Declinada', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=RAz8vEF1cUs', isStandard: true },
  { name: 'Abdominal Supra no Banco Lombar', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=4dEVMa6EjY8', isStandard: true },
  { name: 'Abdominal Supra no Smith', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=zS_t0hJNCP8', isStandard: true },
  { name: 'Abdominal Oblíquo no Solo Cruzado', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=eZUGQw5IsZw', isStandard: true },
  { name: 'Abdominal Oblíquo no Banco Lombar', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=2cxhohPX0CI', isStandard: true },
  { name: 'Abdominal Oblíquo no Banco Declinado', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=hwHDwdgmoEo', isStandard: true },
  { name: 'Abdominal Oblíquo Lateral', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=-WjHb4OEpLM', isStandard: true },
  { name: 'Abdominal Oblíquo Suspenso na Barra', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=ifR5CTlf96Y', isStandard: true },
  { name: 'Abdominal Pára-brisa', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=CbrAdr-Yop4', isStandard: true },
  { name: 'Abdominal Vela com Caneleira', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=R9QCQJ26RBY', isStandard: true },
  { name: 'Prancha em Decúbito Lateral', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=YEo9XbUPvYQ', isStandard: true },
  { name: 'Prancha em Decúbito Ventral', category: 'Core', videoUrl: 'https://www.youtube.com/watch?v=12XgoKciaDo', isStandard: true },

  // ALONGAMENTOS
  { name: 'Alongamento de Panturrilha', category: 'Alongamento', videoUrl: 'https://www.youtube.com/watch?v=5IbiRnOydcs', isStandard: true },
  { name: 'Alongamento de Posteriores de Coxa', category: 'Alongamento', videoUrl: 'https://www.youtube.com/watch?v=AVJTpFzBRAI', isStandard: true },
  { name: 'Alongamento de Trapézio', category: 'Alongamento', videoUrl: 'https://www.youtube.com/watch?v=BgH7VPRoK-c', isStandard: true },
  { name: 'Alongamento de Costas', category: 'Alongamento', videoUrl: 'https://www.youtube.com/watch?v=HdVynhU6PKk', isStandard: true },
  { name: 'Alongamento de Tríceps', category: 'Alongamento', videoUrl: 'https://www.youtube.com/watch?v=ZVliRZwXnaM', isStandard: true },
  { name: 'Alongamento de Quadríceps', category: 'Alongamento', videoUrl: 'https://www.youtube.com/watch?v=aszwGAdZTy4', isStandard: true },
  { name: 'Alongamento de Peitoral', category: 'Alongamento', videoUrl: 'https://www.youtube.com/watch?v=ukxYrleGDZE', isStandard: true },
  { name: 'Alongamento de Ombros', category: 'Alongamento', videoUrl: 'https://www.youtube.com/watch?v=X8rQh42_ixA', isStandard: true },
  { name: 'Alongamento de Bíceps', category: 'Alongamento', videoUrl: 'https://www.youtube.com/watch?v=UPTo15nRr8A', isStandard: true },

  // EXTRA / OUTROS
  { name: 'Hiperextensão Lombar no Banco', category: 'Costas', videoUrl: 'https://www.youtube.com/watch?v=ds9aX5XGBa0', isStandard: true },
  { name: 'Mergulho nas Paralelas', category: 'Braços', videoUrl: 'https://www.youtube.com/watch?v=OPyI6B68tHw', isStandard: true },
];

export const CATEGORIES = ['Todos', 'Peito', 'Costas', 'Pernas', 'Glúteo', 'Ombros', 'Braços', 'Core', 'Alongamento'];
