
export interface LibraryExercise {
  id?: string;
  name: string;
  category: string;
  videoUrl?: string;
}

export const EXERCISES_DB: LibraryExercise[] = [
  // PEITO
  { name: 'Supino Reto com Barra', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/tuwHzzPdaGc?rel=0&modestbranding=1' },
  { name: 'Supino Reto com Barra (Pegada Fechada)', category: 'Peito' },
  { name: 'Supino Reto com Barra (Pegada Aberta)', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/YQnZuQLnJ3k?rel=0&modestbranding=1' },
  { name: 'Supino Reto com Halteres', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/dGqI0Z5ul4k?rel=0&modestbranding=1' },
  { name: 'Supino Inclinado com Halteres (45°)', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/8nNi8jbbUPE?rel=0&modestbranding=1' },
  { name: 'Supino Inclinado com Barra (45°)', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/uIzbJX5EVIY?rel=0&modestbranding=1' },
  { name: 'Supino Declinado com Barra', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/oIgci8aNsG0?rel=0&modestbranding=1' },
  { name: 'Supino Declinado com Halteres', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/5pDbtYmX5fM?rel=0&modestbranding=1' },
  { name: 'Supino no Smith (plano)', category: 'Peito' },
  { name: 'Supino Inclinado no Smith', category: 'Peito' },
  { name: 'Supino Declinado no Smith', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/W6Z2HY8_lDU?rel=0&modestbranding=1' },
  { name: 'Supino na Máquina (Chest Press)', category: 'Peito' },
  { name: 'Supino Inclinado na Máquina', category: 'Peito' },
  { name: 'Supino Declinado na Máquina', category: 'Peito' },
  { name: 'Crucifixo no Banco Plano com Halteres', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/-lcbvOddoi8?rel=0&modestbranding=1' },
  { name: 'Crucifixo Inclinado com Halteres', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/beazxb8q-SA?rel=0&modestbranding=1' },
  { name: 'Crucifixo Declinado com Halteres', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/4ahnfPhKoFo?rel=0&modestbranding=1' },
  { name: 'Crucifixo na Máquina (Fly Machine)', category: 'Peito' },
  { name: 'Crossover na Polia (altura média)', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/OPYrUGZL8nU?rel=0&modestbranding=1' },
  { name: 'Crossover na Polia Alta', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/JHqmhZ12rr0?rel=0&modestbranding=1' },
  { name: 'Crossover na Polia Baixa', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/8YjdqeIXPUQ?rel=0&modestbranding=1' },
  { name: 'Pullover com Halteres', category: 'Peito' },
  { name: 'Pullover no Cabo', category: 'Peito' },
  { name: 'Flexão de Braço Tradicional', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/KEFQyLkDYtI?rel=0&modestbranding=1' },
  { name: 'Flexão de Braço com Pegada Fechada', category: 'Peito' },
  { name: 'Flexão de Braço com Pegada Larga', category: 'Peito', videoUrl: 'https://www.youtube.com/embed/U8O_qJ1yUdA?rel=0&modestbranding=1' },
  { name: 'Paralelas (Foco Peito)', category: 'Peito' },

  // COSTAS
  { name: 'Barra Fixa (Pegada Pronada)', category: 'Costas' },
  { name: 'Barra Fixa (Pegada Supinada)', category: 'Costas' },
  { name: 'Barra Fixa (Pegada Neutra)', category: 'Costas' },
  { name: 'Puxada Frontal na Polia (Pegada Aberta)', category: 'Costas' },
  { name: 'Puxada Frontal na Polia (Pegada Fechada)', category: 'Costas' },
  { name: 'Puxada na Polia com Triângulo', category: 'Costas' },
  { name: 'Remada Curvada com Barra', category: 'Costas' },
  { name: 'Remada com Halteres (Unilateral)', category: 'Costas' },
  { name: 'Remada Unilateral (Serrote)', category: 'Costas' },
  { name: 'Remada Baixa no Cabo', category: 'Costas' },
  { name: 'Remada Alta no Cabo', category: 'Costas' },
  { name: 'Remada na Máquina (Row Machine)', category: 'Costas' },
  { name: 'Remada Cavalinho', category: 'Costas' },
  { name: 'Pulldown no Aparelho', category: 'Costas' },
  { name: 'Pulldown com Corda', category: 'Costas' },
  { name: 'Face Pull na Polia', category: 'Costas' },
  { name: 'Superman (Isometria)', category: 'Costas' },
  { name: 'Bom Dia (Good Morning)', category: 'Costas' },
  { name: 'Hiperextensão na Máquina', category: 'Costas' },
  { name: 'Hiperextensão no Banco', category: 'Costas' },
  { name: 'Levantamento Terra Romeno (ênfase lombar)', category: 'Costas' },
  { name: 'Levantamento Terra', category: 'Costas' },
  { name: 'Extensão Lombar', category: 'Costas' },
  { name: 'Crucifixo Inverso', category: 'Costas' },

  // PERNAS
  { name: 'Agachamento Livre', category: 'Pernas' },
  { name: 'Leg Press 45', category: 'Pernas' },
  { name: 'Agachamento Hack', category: 'Pernas' },
  { name: 'Cadeira Extensora', category: 'Pernas' },
  { name: 'Cadeira Flexora', category: 'Pernas' },
  { name: 'Mesa Flexora', category: 'Pernas' },
  { name: 'Levantamento Stiff', category: 'Pernas' },
  { name: 'Afundo com Halteres', category: 'Pernas' },
  { name: 'Passada', category: 'Pernas' },
  { name: 'Agachamento Sumô', category: 'Pernas' },
  { name: 'Cadeira Adutora', category: 'Pernas' },
  { name: 'Panturrilha em Pé (Máquina)', category: 'Pernas' },
  { name: 'Panturrilha Sentado (Cavalinho)', category: 'Pernas' },

  // GLÚTEO
  { name: 'Elevação Pélvica', category: 'Glúteo' },
  { name: 'Extensão de Quadril no Cabo', category: 'Glúteo' },
  { name: 'Abdução de Quadril no Cabo', category: 'Glúteo' },
  { name: 'Agachamento Búlgaro', category: 'Glúteo' },
  { name: 'Glúteo Máquina', category: 'Glúteo' },
  { name: 'Cadeira Abdutora', category: 'Glúteo' },

  // OMBROS
  { name: 'Desenvolvimento com Barra (em Pé)', category: 'Ombros' },
  { name: 'Desenvolvimento com Halteres (em Pé)', category: 'Ombros' },
  { name: 'Desenvolvimento com Halteres (Sentado)', category: 'Ombros' },
  { name: 'Desenvolvimento no Smith', category: 'Ombros' },
  { name: 'Desenvolvimento na Máquina (Shoulder Press)', category: 'Ombros' },
  { name: 'Elevação Lateral com Halteres', category: 'Ombros' },
  { name: 'Elevação Lateral na Polia', category: 'Ombros' },
  { name: 'Elevação Lateral na Máquina', category: 'Ombros' },
  { name: 'Elevação Frontal com Halteres', category: 'Ombros' },
  { name: 'Elevação Frontal com Barra', category: 'Ombros' },
  { name: 'Elevação Frontal na Polia', category: 'Ombros' },
  { name: 'Crucifixo Inverso na Máquina (Rear Delt Fly)', category: 'Ombros' },
  { name: 'Face Pull (trabalha posterior)', category: 'Ombros' },
  { name: 'Encolhimento de Ombros com Halteres', category: 'Ombros' },
  { name: 'Encolhimento de Ombros com Barra', category: 'Ombros' },
  { name: 'Desenvolvimento Arnold', category: 'Ombros' },

  // BRAÇOS (Bíceps + Tríceps)
  { name: 'Rosca Direta com Barra', category: 'Braços' },
  { name: 'Rosca Direta com Barra (pegada invertida)', category: 'Braços' },
  { name: 'Rosca Direta com Halteres (simultânea)', category: 'Braços' },
  { name: 'Rosca Alternada com Halteres', category: 'Braços' },
  { name: 'Rosca Scott com Barra na Máquina', category: 'Braços' },
  { name: 'Rosca Scott com Halteres', category: 'Braços' },
  { name: 'Rosca no Banco Scott com Barra W', category: 'Braços' },
  { name: 'Rosca no Cabo (Polia)', category: 'Braços' },
  { name: 'Rosca Martelo com Halteres', category: 'Braços' },
  { name: 'Rosca 21 (21s)', category: 'Braços' },
  { name: 'Rosca Inversa com Barra', category: 'Braços' },
  { name: 'Concentration Curl com Halteres', category: 'Braços' },
  { name: 'Rosca Concentrada', category: 'Braços' },
  { name: 'Tríceps Pulley (Barra Reta)', category: 'Braços' },
  { name: 'Tríceps Corda na Polia Alta', category: 'Braços' },
  { name: 'Tríceps Barra na Polia Alta', category: 'Braços' },
  { name: 'Tríceps Testa com Barra', category: 'Braços' },
  { name: 'Tríceps Testa com Halteres', category: 'Braços' },
  { name: 'Tríceps Francês com Halteres', category: 'Braços' },
  { name: 'Tríceps Francês no Cabo', category: 'Braços' },
  { name: 'Coice de Tríceps com Halteres', category: 'Braços' },
  { name: 'Mergulho nas Paralelas', category: 'Braços' },
  { name: 'Mergulho no Banco (Bench Dips)', category: 'Braços' },
  { name: 'Close-Grip Bench Press (Supino Fechado)', category: 'Braços' },
  { name: 'Tríceps Pulley (Barra Reta)', category: 'Braços' },
  { name: 'Tríceps Francês', category: 'Braços' },
  { name: 'Mergulho (Dips)', category: 'Braços' },

  // CORE
  { name: 'Abdominal Reto Tradicional', category: 'Core' },
  { name: 'Abdominal Infra (Elevação de Pernas)', category: 'Core' },
  { name: 'Abdominal Supra (Crunch)', category: 'Core' },
  { name: 'Abdominal Oblíquo', category: 'Core' },
  { name: 'Abdominal Bicicleta', category: 'Core' },
  { name: 'Abdominal na Máquina', category: 'Core' },
  { name: 'Abdominal no Cabo', category: 'Core' },
  { name: 'Prancha (Isometria)', category: 'Core' },
  { name: 'Prancha Lateral', category: 'Core' },
  { name: 'Ab Wheel (Roda Abdominal)', category: 'Core' },
  { name: 'Crunch no Banco Declinado', category: 'Core' },
  { name: 'Elevação de Pernas na Barra', category: 'Core' },
  { name: 'Abdominal Supra', category: 'Core' },
  { name: 'Abdominal no Pulley', category: 'Core' },
  { name: 'Russian Twist', category: 'Core' },
];

export const CATEGORIES = ['Todos', 'Peito', 'Costas', 'Pernas', 'Glúteo', 'Ombros', 'Braços', 'Core'];
